#
# TABLE STRUCTURE FOR: desserts
#

DROP TABLE IF EXISTS `desserts`;

CREATE TABLE `desserts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `type` varchar(100) NOT NULL,
  `price` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (1, 'aut', 'Quia et aut animi perferendis expedita. Ut voluptatem minima suscipit consequatur ducimus excepturi. Error voluptate maxime doloremque voluptatem accusantium. Est est consequatur aut numquam dolorem expedita.', 'est', 40);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (2, 'nihil', 'Quod velit enim natus. Quasi optio non qui. Quidem aliquid veniam porro rerum.', 'hic', 2);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (3, 'voluptas', 'Ullam quis non quos eum in beatae. Aut iusto sunt id quibusdam in error nemo necessitatibus. Rem deleniti et unde atque molestiae quam consectetur. Delectus qui velit vero maiores pariatur. Voluptas autem in adipisci molestiae nemo sed nemo.', 'molestias', 28);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (4, 'saepe', 'Porro eum voluptas aut rerum et consequatur. Et iure tempora odit inventore eveniet illo ipsam. Quia quo quia sed. Culpa voluptatum occaecati ducimus illo.', 'unde', 50);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (5, 'similique', 'Et ea ut qui reiciendis dolores sit. Omnis veniam numquam ad qui. Non quia delectus iusto eius tempore. Omnis cumque voluptas et et laudantium.', 'velit', 27);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (6, 'non', 'Officiis pariatur labore architecto quo illo sit eveniet consequuntur. Eum nesciunt sunt molestiae in asperiores iure quidem. Sit excepturi repellat soluta saepe illo reiciendis. Minima aut harum hic eos.', 'est', 78);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (7, 'voluptatem', 'Odio ea blanditiis sed aliquam quo nostrum unde. Vel aut et fuga et assumenda. Incidunt autem in vitae. Modi laudantium voluptatibus eos autem.', 'hic', 77);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (8, 'vitae', 'Mollitia dolorum ea nulla. Cupiditate fugit alias quo voluptas quam.', 'molestias', 55);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (9, 'necessitatibus', 'In inventore odit aut qui vitae nisi praesentium autem. Est excepturi reprehenderit sed dolorem. Fugiat consequuntur labore delectus rerum magnam. Tenetur blanditiis similique ea.', 'unde', 96);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (10, 'libero', 'Sit dolorem et dolor harum esse beatae quam corporis. Est eligendi quibusdam et enim et libero. Minima ea pariatur qui cumque. Aspernatur placeat veritatis voluptatem impedit iusto maxime illum quia.', 'velit', 99);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (11, 'provident', 'Similique natus repellendus hic architecto. Et velit blanditiis voluptas provident ipsa non. Incidunt nemo velit est. Qui tenetur laboriosam et unde.', 'est', 13);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (12, 'natus', 'Quaerat qui debitis rerum consequatur mollitia consequatur. Et minima repudiandae non voluptatibus. Dolorem dolorem animi qui voluptatem quas ipsam necessitatibus. Illo numquam officia corrupti dolorum enim inventore quo.', 'hic', 39);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (13, 'ipsa', 'In exercitationem impedit sit ex at deleniti. Praesentium qui animi dolor repudiandae. Accusantium aut dolor occaecati excepturi ut et. Molestiae dolorem sint sapiente sed a. Molestiae vel quos quaerat.', 'molestias', 63);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (14, 'quis', 'Nesciunt pariatur consectetur voluptas aspernatur vel corrupti. Magnam vel sequi veniam. Consequatur eius sapiente illum minima quis eligendi ad fugiat. Quos rerum nesciunt cumque ut totam earum autem eveniet.', 'unde', 75);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (15, 'aperiam', 'Ratione soluta ipsum recusandae rerum velit. Quisquam nulla dolorem at cum tempora error eaque. Et asperiores voluptatem natus occaecati sit et similique.', 'velit', 86);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (16, 'voluptates', 'Consequatur ea labore soluta tempore non quis ut. Est cupiditate nihil harum quidem asperiores. Repellendus quisquam aut numquam consequuntur repellendus qui molestiae. Quis quas ipsam deleniti nostrum cumque dolor odio.', 'est', 18);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (17, 'rerum', 'Veniam voluptas ab at consequatur eos. Non itaque qui nihil excepturi. Velit quisquam omnis porro tenetur itaque cumque dolor.', 'hic', 75);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (18, 'impedit', 'Veniam dolor delectus officia dolores mollitia. Minima rem qui autem molestias neque sit. Quibusdam rerum excepturi itaque non ratione. Sunt non enim natus tenetur vero voluptates et.', 'molestias', 13);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (19, 'unde', 'Laborum saepe placeat aut quia rerum. Quas quibusdam ut assumenda eum tempora culpa. Eaque omnis et modi deserunt ipsum molestiae est.', 'unde', 71);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (20, 'debitis', 'Est adipisci quas et voluptas. Minus rerum hic et praesentium. Autem mollitia recusandae ea.', 'velit', 65);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (21, 'autem', 'Itaque aut doloribus unde alias magni accusantium aliquam. Non omnis deserunt cumque quia earum velit maiores. Earum tempora ut praesentium.', 'est', 99);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (22, 'ratione', 'Autem veritatis aliquam similique amet nobis consectetur quo. Quaerat quasi mollitia minima beatae nihil commodi dicta suscipit. Id dolorem ratione pariatur odit enim qui animi.', 'hic', 28);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (23, 'esse', 'Voluptatem voluptas delectus quis tempora voluptate inventore. Et eos corporis provident repellendus non nesciunt esse. Et architecto voluptatem quas magni. Commodi ut et qui et.', 'molestias', 56);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (24, 'sed', 'Repellat est nihil sed earum officia. Quis cum assumenda tempore laboriosam aut minus cum tenetur. Ea dolorem odit velit fugiat nulla. Sint omnis esse dolor itaque et aliquam hic exercitationem.', 'unde', 32);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (25, 'at', 'Ut ab odit quia explicabo. Qui corporis deleniti dolor explicabo aut. Omnis tempora est aperiam hic tempore dolor. Quibusdam ex incidunt quo ut voluptas rerum.', 'velit', 23);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (26, 'enim', 'Reiciendis minus corporis fugiat dolorum ipsam est corrupti. Ab optio adipisci dicta. Sed eos sunt omnis accusamus.', 'est', 52);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (27, 'et', 'Consequatur animi non pariatur id porro veritatis illum. Maxime ea unde laudantium quae quia reprehenderit autem. Dicta magni cumque magnam officiis. Optio natus autem facere voluptatem tempore quo quis.', 'hic', 39);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (28, 'nam', 'Voluptatem minus unde velit nihil. Nulla sint nesciunt est aliquam cupiditate expedita voluptatem. Porro est eaque in et. Ut magni autem corrupti quisquam ullam et.', 'molestias', 47);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (29, 'nobis', 'Rerum non explicabo et optio earum. Laudantium quo voluptatem reiciendis voluptatem et aut. Voluptate quidem sit impedit.', 'unde', 25);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (30, 'dolorem', 'Mollitia nobis non et ducimus placeat est molestias. Quasi minima odit autem molestiae ut. Ducimus rerum esse aut impedit ducimus. Beatae vel voluptatem id in. Culpa ut consequuntur nostrum.', 'velit', 76);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (31, 'quo', 'Debitis quia odit unde occaecati repellendus tempora. Nulla excepturi debitis vel reprehenderit. Ex incidunt labore et esse enim repudiandae.', 'est', 48);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (32, 'est', 'Illum provident et iusto animi. Ut incidunt et voluptatem cum repudiandae officia. Assumenda quo modi est repellendus dolores.', 'hic', 43);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (33, 'veritatis', 'Iure vel natus necessitatibus culpa voluptas quidem eius. Nobis iste unde fuga aut.', 'molestias', 84);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (34, 'sit', 'Esse ducimus nam repellat. Id qui reprehenderit reiciendis. Iste ducimus perferendis culpa ducimus. Quia consectetur ea molestiae alias perferendis neque.', 'unde', 32);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (35, 'molestiae', 'Nulla pariatur ex reprehenderit vel qui et. Dolores in et rerum adipisci. Non consectetur dolor non aperiam optio dolor consectetur. Nam nobis tempore et a nisi et expedita.', 'velit', 51);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (36, 'in', 'Inventore dolorem doloribus accusantium dolor incidunt eaque officiis vel. Cum aliquid occaecati delectus quibusdam.', 'est', 71);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (37, 'nulla', 'Minima veniam quis blanditiis maxime nihil eaque. Libero cumque voluptatem qui aperiam ut est qui. Sed tenetur voluptates minima aperiam non.', 'hic', 45);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (38, 'atque', 'Ipsam nisi autem vero. Itaque velit a ab illo culpa. Accusamus et consequatur et iusto libero quis minus labore. Perferendis assumenda quae eveniet dolorem laborum dolores molestias.', 'molestias', 84);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (39, 'ipsam', 'Sint a excepturi quis quis sint. Aspernatur excepturi nobis et. Et sint rerum amet dolorem. Iste reiciendis maiores quae.', 'unde', 66);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (40, 'tempore', 'Sunt rerum optio non earum aspernatur aliquid nam. Eos illo quam ex dolorum. Molestiae nostrum aut aut itaque quasi dolor et.', 'velit', 78);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (41, 'ex', 'Officiis ea repellat soluta a nostrum dolor nostrum vel. Autem repellendus labore ut rerum earum. Cum vel commodi error voluptas provident.', 'est', 29);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (42, 'distinctio', 'Unde mollitia dolor tenetur dolorem occaecati sit et eum. Ut facere illum adipisci praesentium doloremque vel. Sapiente molestiae quas enim laborum et qui. Culpa ut ut perferendis iste dicta voluptatem voluptas et.', 'hic', 10);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (43, 'id', 'Molestiae velit et minima quo dolorem explicabo. Magnam voluptatibus est asperiores. Reiciendis aliquam itaque molestiae non consequatur perferendis ullam. Consequuntur est quis harum blanditiis.', 'molestias', 78);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (44, 'soluta', 'Debitis rerum nemo non necessitatibus aut. Aut ex qui enim non et eum quis. Modi error eos in quae voluptatem inventore.', 'unde', 24);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (45, 'optio', 'Enim magnam dolorem unde neque exercitationem. Ipsam excepturi porro et assumenda sit. Perspiciatis cum in consequuntur.', 'velit', 78);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (46, 'dignissimos', 'Voluptatem dolor ad rerum inventore. Iure aut ipsam inventore consectetur nostrum. Omnis eos totam reiciendis modi est.', 'est', 70);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (47, 'eaque', 'In modi porro sint. Dolore et rerum magni corporis velit eveniet sint impedit. Maxime excepturi nostrum fuga voluptatem adipisci sed quas. Eum qui aut quia et dolores.', 'hic', 45);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (48, 'laudantium', 'Qui reprehenderit quasi eos a et placeat. Velit repudiandae et nobis est laudantium sunt qui. Ea praesentium est reprehenderit eius. Culpa non veniam et dicta doloribus consequatur ad.', 'molestias', 26);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (49, 'doloremque', 'Modi distinctio voluptatum a sint optio est. Aperiam tenetur sint beatae voluptas. Quis facilis occaecati rerum sequi laboriosam.', 'unde', 74);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (50, 'voluptatum', 'Et ut velit ullam inventore hic. Nobis expedita est explicabo reprehenderit corporis dolorum expedita. Corporis nam voluptates odio saepe perferendis voluptate. Earum ut magni incidunt suscipit qui est.', 'velit', 32);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (51, 'nostrum', 'Ea saepe quaerat officia quia modi rerum hic. Dolores laboriosam sed tempora perspiciatis. Et quis sapiente eligendi et sunt sint. Libero ea eos at magnam repudiandae.', 'est', 30);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (52, 'totam', 'Necessitatibus soluta aut minus aliquam qui quia qui. Consequatur distinctio ex est commodi id amet. Magnam vel temporibus molestiae.', 'hic', 6);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (53, 'mollitia', 'Et ex occaecati possimus. Veritatis ipsa ad et aspernatur labore. Ut dolores ullam alias et voluptatem officia.', 'molestias', 85);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (54, 'quasi', 'Magnam aliquid sit quos ut. Soluta voluptatem exercitationem explicabo sequi optio. Fuga autem excepturi quia eveniet. Aut omnis culpa voluptas laudantium quia. Qui alias eveniet nostrum velit distinctio alias ea.', 'unde', 84);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (55, 'doloribus', 'Inventore iure tempore facilis repellendus dolor pariatur omnis. Molestiae dignissimos quas omnis odit molestiae. Id ducimus omnis provident maxime molestiae est ducimus. Perspiciatis sint saepe quo omnis sapiente ea.', 'velit', 26);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (56, 'expedita', 'Et dignissimos officiis in et adipisci rerum temporibus. Odio quibusdam repellat aliquid. Sequi maiores nulla et facere.', 'est', 11);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (57, 'officia', 'Necessitatibus deserunt et consectetur aperiam quia. Temporibus esse hic non. Id mollitia et optio reprehenderit quam deleniti. Quod nisi error harum temporibus corrupti quam dolorem. Voluptatibus est expedita quos dolore qui repellendus.', 'hic', 76);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (58, 'aliquam', 'Dolore unde ad maxime sint in quod. Omnis expedita error natus odit. Ipsa aut occaecati dolorem laboriosam quia sit mollitia. In omnis sunt quis. Adipisci perferendis quo perferendis aut.', 'molestias', 90);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (59, 'quam', 'Qui repudiandae doloribus quidem molestiae sed. Deleniti doloribus molestiae qui voluptate ipsam. Recusandae nihil voluptas eveniet perferendis.', 'unde', 93);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (60, 'explicabo', 'Velit corporis eum nemo fugiat iste necessitatibus. Debitis perspiciatis accusamus tenetur. Placeat voluptate magni doloribus tempore dolores voluptas quam.', 'velit', 82);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (61, 'cumque', 'Quam aut minus aperiam placeat. Commodi sequi impedit fugit aut dolores libero cum. Reprehenderit ut rerum non adipisci quam. Libero voluptatibus autem omnis sunt dolores dolores iusto.', 'est', 8);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (62, 'consequatur', 'Enim modi doloremque animi. Quasi dolorum nesciunt quia odit. Doloribus provident odit aut fugiat.', 'hic', 58);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (63, 'qui', 'Voluptatibus est labore id harum inventore. Incidunt ad ex id commodi ut aliquam suscipit sapiente. Enim illum veritatis labore doloribus quo.', 'molestias', 76);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (64, 'reiciendis', 'Vitae nostrum nemo eum illum quia ut. Consequatur id laboriosam id ipsam. Omnis eum architecto dolor voluptatem alias. Ut natus deserunt minus sunt.', 'unde', 62);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (65, 'quod', 'Qui dolor consequatur ducimus voluptate ut. Recusandae est blanditiis itaque eius quidem. Autem voluptates illum dolorem est. Cum vel autem adipisci.', 'velit', 29);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (66, 'odit', 'Nulla molestias in ea natus. Libero laborum culpa cupiditate provident. Voluptas debitis porro doloribus repellendus autem dicta sit.', 'est', 34);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (67, 'fugiat', 'A nam non non quos eos. A voluptatem totam aut veritatis mollitia unde. Omnis rerum dicta temporibus ipsa repellat. Veritatis et nemo accusamus ea.', 'hic', 27);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (68, 'incidunt', 'Placeat possimus sapiente porro iste reiciendis tenetur. Dolore quia dignissimos ut dolores ex ipsa cupiditate ducimus. Et eum cumque eligendi sunt est provident velit unde. Expedita ipsam suscipit animi.', 'molestias', 80);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (69, 'quia', 'Hic quisquam dicta sint nemo explicabo dolor accusamus. Et quam unde rerum exercitationem. Nihil nesciunt voluptatem autem corporis magni molestias.', 'unde', 47);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (70, 'velit', 'Id doloribus assumenda quia labore cum rerum. Inventore sint aliquid recusandae nihil commodi iusto. Sit repudiandae repellendus libero molestiae ut libero nemo.', 'velit', 20);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (71, 'voluptatibus', 'Magni molestias qui in ut sequi quia labore numquam. Ducimus ex quos quaerat et dicta ex consectetur. Repellendus praesentium fugit quaerat molestias atque ab. Minima modi voluptas provident culpa in. Fuga necessitatibus sunt rerum.', 'est', 10);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (72, 'minima', 'Animi dolore iste doloremque placeat aliquid et repellat. Quaerat dolorem voluptatem molestiae et sequi. Veritatis dolor eveniet sunt eaque veniam consequatur numquam eum. Non inventore sed aut facere minus.', 'hic', 61);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (73, 'quae', 'Voluptas et amet voluptatibus placeat libero voluptatem. Iure fugit hic laboriosam delectus consequatur.', 'molestias', 41);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (74, 'sint', 'Natus odit consequatur iste quis. Corrupti saepe quis sit vitae sed.', 'unde', 59);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (75, 'perspiciatis', 'Ab sunt ea sit voluptate quibusdam commodi optio. Deserunt vero tenetur ut perspiciatis mollitia porro. Voluptatem repellendus odit quia quis dolorum et non. Nemo voluptas odit reiciendis voluptatum dolore.', 'velit', 88);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (76, 'dolores', 'Reiciendis non consequatur voluptas vel quo. Cupiditate velit quasi consequuntur quos voluptates consequatur et. Voluptas rerum eum doloribus aut modi.', 'est', 89);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (77, 'quaerat', 'Nisi labore mollitia quia soluta cum provident quia voluptatem. Numquam ratione voluptas voluptatum inventore beatae. Voluptatum et illum repellat aperiam ad tenetur. Incidunt incidunt omnis laborum maxime voluptatem alias.', 'hic', 47);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (78, 'hic', 'Vero et omnis nisi nihil iure aspernatur et suscipit. Soluta ut facere provident perferendis dolorum quas. Aut cupiditate labore ut eos itaque. Reiciendis aliquid et quis dolores deserunt.', 'molestias', 9);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (79, 'sequi', 'Et illo hic deleniti et et soluta nostrum ducimus. Omnis sunt et consequatur voluptatem dolore quo. Magnam ex consequatur tempora iure. Totam voluptas molestias eum ab totam inventore.', 'unde', 21);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (80, 'excepturi', 'Recusandae ipsum sit qui dolorum tenetur nobis fugiat aut. Inventore quidem occaecati qui rerum repellat corrupti quia. Nulla consequatur cupiditate enim numquam eaque maxime.', 'velit', 46);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (81, 'laboriosam', 'Neque temporibus explicabo culpa. Blanditiis qui quia commodi delectus. Qui officia adipisci repudiandae ut quasi.', 'est', 69);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (82, 'omnis', 'Enim non harum cumque numquam eaque doloremque odit. Totam nisi et sit consequatur voluptatem. Quam sed ipsa veniam eveniet similique iste. Eum blanditiis voluptatem animi ab blanditiis.', 'hic', 7);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (83, 'beatae', 'Quasi provident perferendis voluptatem temporibus consectetur modi. Sint ut itaque in qui esse corporis iure. Amet qui dolorem animi voluptatibus consequatur facilis saepe. Libero voluptas esse adipisci expedita facere.', 'molestias', 30);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (84, 'maxime', 'Aut necessitatibus et rem quis dolores dolor sapiente. Et eum nulla assumenda quo. Sunt aut explicabo est est itaque ipsam sit. Ut necessitatibus iusto aut aut autem ut.', 'unde', 48);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (85, 'ut', 'Quidem repellendus quidem qui cum. Praesentium debitis sint ea repellendus quasi libero. Odit consequatur et eius ut consequatur. Assumenda quis doloremque nihil mollitia et.', 'velit', 78);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (86, 'eos', 'Dolorum aliquid qui et in quia. Ipsum deleniti dolorem porro optio reprehenderit a. Officiis earum sed cum recusandae reiciendis autem.', 'est', 66);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (87, 'blanditiis', 'Et magnam maiores dicta voluptatem. Neque voluptatem ut qui qui dolores qui et officiis. Est consequatur fuga doloribus deserunt.', 'hic', 33);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (88, 'magnam', 'Cupiditate tenetur sint soluta quo non natus. Enim natus officia dolores aut eum mollitia. Excepturi sunt nihil neque labore.', 'molestias', 75);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (89, 'accusamus', 'Molestias ab magnam est facere esse sit vitae. Eveniet expedita dolorem cupiditate repudiandae. Blanditiis explicabo beatae quia nihil. Quaerat labore id cupiditate maiores.', 'unde', 83);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (90, 'vero', 'Amet dolores ipsa animi nobis quod. Tenetur at dignissimos rerum expedita non sequi. Nam a quidem adipisci alias id magni ratione. Architecto similique at odit blanditiis voluptatem.', 'velit', 34);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (91, 'occaecati', 'Facere ut minima dolorem facere. Voluptatum quos pariatur totam illo. Voluptate sequi omnis qui error.', 'est', 9);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (92, 'error', 'Nobis vel cupiditate dolores illum libero adipisci porro. Ea praesentium provident sint quis molestiae. Et modi provident eligendi dolor voluptas.', 'hic', 88);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (93, 'dolorum', 'Odio distinctio laborum cupiditate quia veritatis aspernatur. Eos in et voluptatem ullam et voluptatem atque. Consequatur autem nihil sed quaerat occaecati sit laudantium. Et laborum dignissimos minus laborum voluptas.', 'molestias', 79);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (94, 'ducimus', 'Mollitia natus voluptatem nemo et et consequuntur. Est nostrum et explicabo earum impedit. Optio nemo voluptatem ratione voluptas soluta rerum adipisci nemo.', 'unde', 62);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (95, 'veniam', 'Consectetur sit molestiae occaecati sed eos ea aperiam. Ullam consequatur cumque modi numquam aliquam. Dolores corporis sed assumenda dolorem nisi rerum. Officia excepturi vel sed dolor consectetur.', 'velit', 32);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (96, 'repellat', 'Nemo quam quasi et dolorem molestiae. Totam ratione repudiandae laudantium est. Aperiam vitae quasi facere velit hic. Rerum excepturi iusto aut eos non fugiat.', 'est', 71);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (97, 'facilis', 'Laboriosam ab tenetur eligendi labore eos at impedit eaque. Harum maiores et ducimus autem et iste quod molestiae. Blanditiis molestias nisi quia veritatis voluptatem.', 'hic', 6);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (98, 'alias', 'Expedita est accusantium aliquid ipsum eos. Et quis harum perferendis eius. Facere natus quo et doloremque quidem voluptatem impedit. Dolorem blanditiis quisquam voluptatem sit dicta id maxime.', 'molestias', 34);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (99, 'eligendi', 'Esse corporis placeat voluptatem consequatur laborum. Et praesentium vel ab. Nostrum laborum molestias officiis id et voluptatum pariatur.', 'unde', 1);
INSERT INTO `desserts` (`id`, `name`, `description`, `type`, `price`) VALUES (100, 'pariatur', 'Beatae fugit alias sed molestiae culpa. Non nihil illum officiis dolore porro eos placeat.', 'velit', 2);


#
# TABLE STRUCTURE FOR: drinks
#

DROP TABLE IF EXISTS `drinks`;

CREATE TABLE `drinks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` int(11) NOT NULL,
  `type` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (1, 'vel', 'Voluptates blanditiis corrupti veritatis repellendus eum. Amet eaque sint voluptatibus quas. Minus quo ex iste autem.', 0, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (2, 'ut', 'Ducimus molestiae necessitatibus consequuntur maiores repudiandae. Illum a illo omnis doloribus totam eos dignissimos non. Molestiae illo consequatur veniam quo consequatur.', 7048165, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (3, 'consequatur', 'Non aut id molestias. Odio aspernatur ullam quia commodi deserunt temporibus eum alias. In vel sapiente nulla architecto sequi.', 44, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (4, 'dolorem', 'Non sint quaerat quia consequuntur. Ipsum et maiores et qui sit fugiat. Ducimus nesciunt quis officiis beatae explicabo. A rerum labore aspernatur atque sed nesciunt laudantium. Sint eligendi vel possimus qui excepturi.', 629124, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (5, 'eligendi', 'Non quos alias qui ducimus est. Quia occaecati culpa modi quaerat totam. Ipsa quasi sed eum laborum. Ex quia similique accusamus nobis magni rerum quo.', 474, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (6, 'facere', 'Voluptatem ut veritatis perferendis ipsum voluptate sit et. Vel voluptates delectus quia quos similique. Enim ipsam ducimus in quia nihil repudiandae.', 7, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (7, 'tempora', 'Eos voluptatem nihil commodi libero impedit. Deleniti aspernatur natus illum dolorem omnis. Cupiditate dolores est assumenda et laudantium dolor. Nostrum officiis porro quo nam.', 9, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (8, 'laborum', 'Sit hic illum nesciunt omnis et. Ad inventore cum et error iste. Nemo sed officiis unde alias quia.', 86171685, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (9, 'explicabo', 'Commodi aut vitae fugit. Vitae rerum enim illo rerum a aliquam voluptatum. Repudiandae totam autem ad culpa. Earum modi et temporibus.', 769, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (10, 'est', 'Harum quaerat dolore sequi nam quia nisi aut et. Nesciunt velit praesentium sunt rerum eum ratione. Aperiam optio quaerat hic a id pariatur.', 7, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (11, 'quia', 'Atque dolorem omnis enim. Impedit ea ut quasi numquam distinctio. Harum iure accusamus aspernatur asperiores quaerat.', 7522, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (12, 'nihil', 'Explicabo voluptatum soluta facere non praesentium eveniet. Quaerat impedit occaecati adipisci. Et eius delectus officia ea.', 64535, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (13, 'ea', 'Vel fugiat iste nihil. In exercitationem est dolor quis beatae fuga et. Ut qui enim consequatur ut maiores autem.', 488266, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (14, 'debitis', 'Culpa totam aspernatur sit deserunt ut harum molestias. Aliquid aut quos ipsa cumque et quisquam totam. Deserunt eos corporis molestias deserunt.', 0, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (15, 'eos', 'Reiciendis sequi dolorem nesciunt aut in ut. Praesentium iusto nisi amet labore sunt sunt. Similique consequuntur quidem et sequi.', 3, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (16, 'maiores', 'Ea vel nulla unde nemo. Enim provident et vel quaerat deleniti. Omnis dolorem sed voluptatibus tempora velit error est.', 13264, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (17, 'natus', 'Aliquam voluptas est culpa similique rerum sed delectus. Illo numquam voluptas laboriosam ipsa voluptates sed incidunt. Omnis optio praesentium fuga.', 10541165, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (18, 'ut', 'Qui ab aut consectetur. A molestiae quo et doloribus ipsum. Sequi suscipit dolor sit non tenetur. Sint porro eos aliquam quia. Omnis rerum in animi nulla culpa odit laboriosam saepe.', 1, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (19, 'dolorum', 'Qui quas porro officia consequuntur unde. Fugit cupiditate enim a quo quia adipisci nobis. Consequuntur distinctio quidem reiciendis quo perspiciatis quod.', 3729018, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (20, 'facilis', 'Eligendi praesentium cumque et nisi. Consequatur deleniti ad quam ut enim sunt. Ut ad in suscipit. Aut doloremque sit ea magni harum itaque voluptate cumque.', 1181917, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (21, 'accusantium', 'Laboriosam laboriosam tempore maiores accusamus aut. Id fugiat officia omnis itaque. Earum quam occaecati aliquam ad ut sint odit eos.', 4333, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (22, 'officia', 'Qui omnis facilis sed quis voluptatem explicabo iure. Dolorem aut et voluptatem qui est exercitationem enim. Saepe aperiam itaque voluptates et aliquam magni aut dolore. Dolores et facilis inventore magnam consectetur velit.', 765076, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (23, 'eaque', 'Necessitatibus sit dolore est labore molestiae ex. Mollitia ad amet id laborum dolor est ex occaecati. Dolor quisquam asperiores dolore delectus et. Nisi porro est sint dolore est.', 548112, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (24, 'adipisci', 'Dignissimos quaerat perspiciatis consequatur perferendis quam. Voluptatibus est similique minus eos occaecati fuga vel nobis. Minus ab commodi reprehenderit aperiam incidunt aut.', 0, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (25, 'et', 'Iure quo vitae cupiditate fugiat. Enim ut labore maxime alias incidunt. Porro omnis accusantium neque architecto.', 50758016, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (26, 'rem', 'Perferendis non explicabo enim sunt eaque id. Atque odit ipsum sint sit neque. Tempora et repellat illum hic. Ex dolore eveniet voluptatem blanditiis qui.', 1879642, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (27, 'voluptatum', 'Aut autem a saepe quidem nam voluptatum. Et sed voluptatem autem suscipit. Vitae labore ullam officia quod consectetur odio et.', 42835612, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (28, 'non', 'Mollitia doloremque voluptates soluta. Tempora tenetur consequuntur consectetur dolor. Maiores eligendi aspernatur blanditiis.', 46953, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (29, 'deserunt', 'Ut praesentium placeat eos commodi. Aut voluptates eaque qui. Beatae iure molestiae repudiandae aut.', 7336, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (30, 'esse', 'Quidem omnis veritatis dolorem et. Et temporibus doloribus perferendis omnis. Odio ut ipsum et blanditiis cupiditate. Architecto maxime non sed at.', 22513713, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (31, 'exercitationem', 'Consectetur at vel ut sunt sit aut. Corporis maiores officiis laudantium cumque aut. Delectus libero soluta praesentium tenetur saepe. Quos sed ab commodi qui consequatur.', 3, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (32, 'dolorem', 'Ullam nulla repellendus mollitia inventore ut ad. Dolorem quis sint libero ad. Autem facilis ipsam et et unde. Ipsa animi ad at dolor repudiandae commodi suscipit. Voluptatem numquam est vitae rerum natus natus ad.', 10, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (33, 'omnis', 'Ipsa aut quia dicta inventore. Aliquam maiores ut et. Rerum aut officiis et molestiae amet provident. Pariatur nostrum alias impedit nisi non voluptas.', 90, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (34, 'molestiae', 'Odit laborum et laudantium iste aut quo. Repellat harum illum omnis sed. Voluptatum natus totam laudantium ut excepturi velit. Eum iste consequatur vel ut odit et ipsam iste.', 535437973, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (35, 'eum', 'Sit cupiditate error velit deserunt ipsum. Non vitae omnis qui omnis non sunt sed voluptates. Veniam aperiam inventore aut.', 35, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (36, 'fugiat', 'Et qui corporis a sint et. Necessitatibus dolor excepturi sint assumenda qui quo fugiat.', 16823, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (37, 'voluptatum', 'Et doloremque accusantium excepturi. Vel qui autem porro voluptatem molestiae. Consequatur necessitatibus harum deserunt atque iure ut dolores.', 15031111, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (38, 'beatae', 'Rerum sit dolore nobis quibusdam. Nemo non accusamus veniam sed perspiciatis consequatur. Dolorem repellendus sint in error. Architecto nostrum fugit asperiores odit quae quia.', 0, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (39, 'perferendis', 'Qui unde aperiam et qui delectus delectus consequatur consequatur. Quam ipsam dolorem qui architecto. Nobis ducimus est corrupti.', 46, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (40, 'asperiores', 'Voluptatum id est et sequi enim. Quaerat ut doloribus iure aut ut ut. Accusantium magni quae et. Est et dignissimos magnam repellat porro neque.', 11480, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (41, 'tempora', 'Voluptas facilis sit modi est eaque mollitia et. Nihil adipisci rerum veniam et. Cupiditate minima tenetur necessitatibus et odit voluptatem est magni.', 4, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (42, 'similique', 'Numquam illum consectetur corporis. Voluptatem voluptatibus voluptatem nihil reprehenderit neque tenetur. Cupiditate illum quo et expedita dolor veritatis. Officiis voluptatem odit minima consequatur facilis optio.', 310, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (43, 'in', 'Qui alias vel harum rerum natus. Sed nulla recusandae consequatur laborum. Nesciunt iure dolore ut est. Ut reiciendis illum amet enim cupiditate nulla.', 186500064, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (44, 'nemo', 'Quam perspiciatis qui aspernatur perferendis. At eveniet qui id expedita dicta. Ipsa qui iusto sunt incidunt omnis labore. Non quasi nihil quos quas.', 1447249, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (45, 'et', 'Est nisi beatae recusandae et atque optio autem. Dolorem voluptatum id tempore vitae et molestias. Impedit et provident eligendi voluptatum placeat provident.', 0, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (46, 'ipsam', 'Dicta fugit maxime ad dolor qui et necessitatibus. Aut officiis et dolores sit tempora officiis magni impedit. Perspiciatis ullam dolorum dicta illo voluptatem mollitia perferendis.', 819, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (47, 'quidem', 'Tempora optio aut vero nobis ea. Perspiciatis qui est commodi ut. Tempore quae id delectus.', 381, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (48, 'esse', 'Autem libero sapiente id harum. Exercitationem accusamus qui illum omnis et qui non. Aliquam quidem tempore ad accusamus amet. Corrupti possimus quis tempora nam non fuga magnam. In qui saepe quas explicabo.', 243398, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (49, 'corporis', 'Eum non ut unde doloremque numquam. Enim excepturi qui sequi accusantium ad sed consequatur. Ullam et vero explicabo sed non.', 89487, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (50, 'eveniet', 'Ea quo ad distinctio tempora numquam sint voluptas. Veniam quisquam et aliquid. Nihil omnis numquam expedita voluptates quis impedit atque. Voluptatem temporibus et molestiae qui voluptatem praesentium. At veritatis rerum numquam impedit velit quibusdam ad.', 88181620, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (51, 'cum', 'Placeat possimus et repellat suscipit doloribus atque quasi doloremque. Natus rem mollitia rerum eaque doloremque nisi nemo. Mollitia dicta voluptas adipisci et itaque suscipit. Dolores adipisci officia neque veritatis.', 152768, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (52, 'et', 'Et facilis mollitia non et suscipit occaecati fuga ad. Quas exercitationem nam voluptatem. Voluptatum reprehenderit facere vel culpa rerum necessitatibus nobis.', 1136907, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (53, 'fugiat', 'Alias recusandae ab sed magnam voluptatem. Quas voluptatibus at occaecati velit eum libero. Ducimus eveniet vel quis sapiente et quis cumque accusamus.', 7, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (54, 'suscipit', 'Eveniet eius tenetur est modi aut quaerat quaerat. Libero ad consequatur itaque rerum ea architecto veritatis.', 12, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (55, 'nemo', 'Magnam delectus occaecati sed est. Fugiat explicabo excepturi doloremque debitis quo. Sit ut voluptatem enim soluta.', 33107330, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (56, 'vero', 'Quis nulla provident ut cum illo tempora corrupti dolores. Blanditiis hic ut sequi pariatur voluptatem. Dolores ipsum qui quasi aliquam. Ea nostrum officiis possimus pariatur.', 2209, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (57, 'ut', 'Architecto dolor sint minus dolorum beatae. Voluptatem error eum dolores vel et aperiam dolores facere. Et perferendis et esse dolor.', 1730967, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (58, 'adipisci', 'Omnis totam qui voluptas et enim. Iste eveniet qui quisquam. Qui animi aspernatur maiores quia. Officiis non tenetur adipisci neque.', 2680, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (59, 'sapiente', 'Sapiente voluptatibus sunt quod praesentium. Non est suscipit nihil velit vel architecto.', 334, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (60, 'ut', 'Aut esse illo ducimus sequi aliquam saepe. Rerum enim id ut aut saepe et aut. Laboriosam repellat deserunt molestias neque nam ea.', 34, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (61, 'qui', 'Qui ut est deleniti illo. Totam quia excepturi et. Maiores modi id et. Iusto numquam aut maxime veritatis sunt dolore. Dolores nostrum fugit veniam animi voluptatem tempore.', 51441, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (62, 'optio', 'Harum modi voluptates sit corporis quidem. Vero dolores expedita quia. Maxime non est aspernatur ipsum sint optio.', 660, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (63, 'autem', 'Pariatur itaque omnis et. Sint adipisci explicabo dolores id velit nisi.', 11834176, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (64, 'sunt', 'Perferendis dolores accusantium qui totam et nostrum aut. Libero porro illo non accusantium blanditiis corporis. Sapiente similique natus quo est.', 0, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (65, 'dolorem', 'Non ut velit natus. Autem tempore deserunt incidunt veritatis. Rerum mollitia vitae eum quia.', 1, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (66, 'et', 'Iusto autem illo alias et. Omnis et dicta et et unde qui quo amet.', 2, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (67, 'voluptatum', 'Omnis aspernatur est eos est quaerat. Voluptas vel et placeat dolores expedita laborum qui. Labore qui non dolore et sit dolor. Doloribus enim officiis magnam voluptatem at.', 41, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (68, 'expedita', 'Animi ratione fuga asperiores blanditiis tempora incidunt vel. Expedita ducimus cupiditate et illo. Dicta nisi nihil optio sequi. Aut odit temporibus voluptatem provident.', 0, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (69, 'ut', 'Consequatur nobis enim commodi quos quia quasi est. Dicta sunt animi et nam sit rerum deserunt. Quaerat ab in id. Nesciunt necessitatibus omnis eligendi voluptatem nulla.', 2, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (70, 'dicta', 'Dolorum nemo rerum ut ut fuga. Labore omnis cupiditate vel error consequatur expedita. Reiciendis qui enim qui voluptas quibusdam ea aut. Ex dolorum quia consequatur repellendus est animi voluptatem.', 7992060, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (71, 'officiis', 'Aut labore aspernatur ipsum fugit non et. Sunt quasi delectus ipsa iusto voluptatum earum enim. Officiis debitis quia eveniet aspernatur occaecati quaerat ea. Pariatur corrupti ea eos voluptatem qui tempora.', 74, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (72, 'consectetur', 'Repellat et dolorum maxime totam et aspernatur. Autem itaque et quas unde. Tempore quas officiis nobis rerum. Sit ut et debitis architecto.', 6, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (73, 'quod', 'Rerum impedit non velit. Voluptas aspernatur eligendi ipsam inventore eos aut facilis. Voluptatem ea et possimus aut quod voluptate vero.', 4975399, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (74, 'nemo', 'Nulla officia dolores laborum dolor. Modi aliquid tempora quis unde autem. Dolorum molestiae hic soluta qui inventore. Non ducimus reiciendis id omnis molestias quibusdam.', 1012, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (75, 'dignissimos', 'Dolor impedit ducimus assumenda et aut. Nobis inventore quia est et sunt dolores. Mollitia modi sequi praesentium non voluptatem impedit excepturi dolorum. Sed non numquam autem doloremque fuga soluta ut.', 421, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (76, 'adipisci', 'Ad non error omnis officia sit et numquam fugiat. Doloremque rerum et voluptas rerum sed expedita. Sint pariatur porro officia qui quo nulla in. Odio ut autem excepturi possimus labore eligendi.', 26, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (77, 'incidunt', 'Iure eius pariatur similique omnis quod vero saepe. Mollitia eius dignissimos at perspiciatis suscipit nostrum repellendus. Qui asperiores et sint recusandae.', 56126, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (78, 'voluptas', 'Placeat possimus cum minima reiciendis quam tempore nemo. Ut deserunt quis sed non. Modi possimus aut veniam dolor enim.', 0, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (79, 'dolorum', 'Et minima quam quae pariatur rem. Quidem qui et voluptatibus doloribus. Quia magnam voluptas ipsa et earum. Dolores quasi et ut quam amet molestias alias.', 0, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (80, 'quia', 'Itaque aliquam voluptas minima aut ea perferendis. Consequatur a fugiat sit id. Numquam facere praesentium porro repellendus laudantium. Reprehenderit ut ducimus et est voluptatem nihil voluptatum.', 306062, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (81, 'et', 'Delectus vero quia qui fugit. Maiores qui consequatur hic molestias. Atque enim iusto nulla totam minima.', 6559037, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (82, 'provident', 'Inventore tempore nulla cum nemo. Et incidunt unde quis neque illum sint placeat commodi. Voluptate ut eaque hic minus et assumenda modi mollitia. Minus nesciunt voluptates qui ut veritatis.', 1, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (83, 'tempora', 'Praesentium et porro non pariatur molestiae et incidunt voluptas. Maxime et et rerum aperiam. Nihil possimus quis laudantium non esse. Molestiae accusamus deleniti maxime officia animi rerum.', 532301163, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (84, 'ut', 'Quas necessitatibus incidunt aperiam eligendi itaque reprehenderit voluptate. Laudantium officia corporis et possimus. Non voluptas libero magnam quia.', 172682183, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (85, 'aut', 'Quidem et qui omnis rerum quos voluptatem. Eaque blanditiis aut ipsam doloremque eius odit. Quis maiores alias minus ducimus a sit omnis. Molestiae quis dolores quo voluptas.', 2790409, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (86, 'et', 'Non laudantium in illum quae debitis quia. Esse qui voluptas aut voluptatem. Ad ullam eius ad neque qui et quo.', 414598742, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (87, 'et', 'Nostrum distinctio sapiente fugiat blanditiis nesciunt. Illo assumenda perferendis est quaerat. Aut voluptatem saepe voluptas error laborum est dolor aut.', 7, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (88, 'adipisci', 'Consequatur ratione fugiat eum rerum. Veniam amet minus eveniet voluptatum officiis quasi. Magnam eum reiciendis non neque. Quas deserunt quia laudantium qui labore voluptatibus qui.', 43933912, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (89, 'et', 'Sapiente minima velit in nam facilis dolores. Tempora reprehenderit at provident quis in. Illo placeat unde quibusdam atque.', 617, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (90, 'vel', 'Repudiandae sed et est. Non ad a eos in cumque maiores. Et sit et aspernatur similique totam dignissimos odit. Magni cum porro velit.', 34645, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (91, 'cumque', 'Sint rerum beatae omnis placeat. Tempora ut voluptas et ullam ut delectus quasi. Aliquam aut quo commodi beatae et illo aliquam. Similique minima vel et sed.', 5, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (92, 'est', 'Enim suscipit doloremque aut aspernatur. Aut commodi possimus ab aspernatur porro ipsam et similique. Aut iusto esse ipsam omnis architecto rerum.', 481, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (93, 'et', 'In corporis et qui rerum. Velit architecto recusandae est. Vel sit aut dolor quia. Cum dicta quasi fugiat vitae et.', 19289, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (94, 'aut', 'Quam atque similique quae. Aut exercitationem non temporibus facilis eveniet. Cumque aut ducimus saepe omnis ab ut dolores quod. Harum dolor qui ex accusamus aut quia.', 15739, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (95, 'delectus', 'Quam quaerat exercitationem eligendi vel non. Eligendi ipsam quam molestiae in illo et officia. Sint non dignissimos eveniet commodi. Rerum consectetur quidem amet.', 7957394, 'velit');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (96, 'in', 'Veritatis fugit et cum ducimus exercitationem. Consequuntur beatae enim commodi debitis. Distinctio veniam quos velit sunt. Et ipsum quae totam vel totam eos. Doloribus omnis voluptatem rem.', 74352, 'est');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (97, 'quam', 'Dolores similique est repudiandae aliquid quia et. Est deserunt vitae assumenda corrupti. Voluptatem quam fuga non ipsum.', 652566164, 'hic');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (98, 'molestias', 'Repudiandae dolor rem saepe. Voluptas adipisci maxime ipsam eius nihil eaque consequatur id. Ea voluptates doloribus enim consectetur et maiores qui. Veniam tempora asperiores fugiat.', 73619994, 'molestias');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (99, 'dolor', 'Reprehenderit debitis ea quidem unde sint. Est magnam ut aut minus. Et voluptatum consequatur debitis id rerum provident. Quo delectus amet est expedita cumque quis corporis.', 1436116, 'unde');
INSERT INTO `drinks` (`id`, `name`, `description`, `price`, `type`) VALUES (100, 'suscipit', 'Aut alias eveniet necessitatibus. Est sed quasi perspiciatis quia rem. Et corrupti occaecati et sed ea nihil. Praesentium sed veritatis est ut error vel consequuntur alias.', 526582, 'velit');


#
# TABLE STRUCTURE FOR: meals
#

DROP TABLE IF EXISTS `meals`;

CREATE TABLE `meals` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` int(11) NOT NULL,
  `type` varchar(100) NOT NULL,
  `is_meal_of_the_day` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (1, 'consequuntur', 'Explicabo maiores fugiat sit sequi iure tempore ab doloribus. Nam temporibus non minima quidem cupiditate. Ut ullam est asperiores in. Voluptas quo quia tenetur.', 625, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (2, 'voluptatem', 'Velit exercitationem error veniam similique tempore vero. Similique nulla qui dicta tenetur nihil. Accusantium illo dolores et doloremque. Maiores laborum voluptatem reiciendis cum ut aperiam.', 40, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (3, 'aliquid', 'Omnis omnis quos nihil pariatur. Quasi iure aut nobis dignissimos. Ut odio aut temporibus sed quia impedit dicta.', 244796029, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (4, 'dolor', 'Libero facilis quisquam ut exercitationem officia iure. Repudiandae sed quaerat modi quae et nemo. Accusantium rerum rerum sint aut. Consequatur consequatur officiis doloremque et debitis.', 59038262, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (5, 'aut', 'Illum dignissimos suscipit pariatur praesentium quia alias enim. Accusamus quaerat ea quidem ut aut natus aut aliquam. Consequatur dignissimos deserunt esse iure sit et. Ad voluptas voluptas quo sapiente. Totam voluptas recusandae autem totam magnam.', 331, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (6, 'odio', 'Enim deleniti voluptas corrupti recusandae. Qui excepturi voluptatem enim doloremque explicabo voluptates. Quos ut nam eligendi voluptatem quaerat. Et deserunt harum quo adipisci rerum nisi.', 145244818, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (7, 'asperiores', 'Est perspiciatis amet rerum nemo. Sit laudantium placeat delectus hic. Sint consectetur dolor facere voluptatem eum. Voluptas rerum et dolore molestiae sed.', 21307210, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (8, 'autem', 'Voluptatibus id sequi minus ut. Soluta laudantium mollitia tempore non natus nisi tempora. Soluta temporibus eveniet cumque omnis necessitatibus est. Eaque accusantium porro et qui voluptatibus.', 356367, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (9, 'et', 'Ducimus unde et dolorum non velit ullam minus ea. Veniam veritatis aut eveniet et incidunt. Ipsam perspiciatis reiciendis animi atque neque nulla. Ut sint eos officia maiores.', 1, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (10, 'reiciendis', 'Et sit eum id repudiandae explicabo. Id dolorem qui et ea.', 5, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (11, 'dolorem', 'Itaque odio voluptate omnis neque rem est rerum. Voluptates quis facere et. Eum at aut quia modi est aliquam. Tempora repellendus laboriosam eum qui et.', 0, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (12, 'molestiae', 'Earum in omnis officia consequuntur est. Et odit dolor vitae sint nobis. Doloremque repudiandae soluta voluptatem eveniet laboriosam ex.', 4, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (13, 'fugit', 'Et nihil voluptates tempora quibusdam. Commodi reiciendis voluptas placeat expedita id aliquid. Deserunt natus ut eos facere rerum praesentium.', 1, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (14, 'quisquam', 'Eos repellendus atque voluptates aperiam sed animi. Recusandae repudiandae eos adipisci voluptas itaque. Libero recusandae et excepturi ad commodi numquam.', 9088, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (15, 'voluptate', 'Omnis voluptas ullam aut saepe quidem voluptatem repellendus. Atque molestiae eligendi praesentium harum explicabo qui. Officia occaecati architecto vero ut ut sunt et. Omnis consectetur fuga et enim ad voluptatibus est corrupti.', 1228886, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (16, 'repellendus', 'Rem temporibus vero ut quisquam. Consequatur nisi dignissimos consequuntur sunt veritatis ut voluptatem. Omnis eius odit sit sint sint qui nam. Et aut architecto laboriosam et sunt incidunt.', 418664, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (17, 'assumenda', 'Vitae quae qui consequatur quam incidunt voluptas. Facere odio qui est id aut labore accusantium. Aut fuga iusto aperiam possimus. Aut maiores enim sint totam hic rem aliquam.', 0, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (18, 'blanditiis', 'Odio a molestiae porro sapiente id quis explicabo. Placeat et voluptatibus dolorem non fugit ut molestias neque. Quibusdam numquam placeat a fugit assumenda odio. Non ut cumque dignissimos cumque sit.', 39743782, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (19, 'numquam', 'Voluptatem aspernatur veniam eos aut. Consequuntur dolore libero dignissimos porro.', 2856, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (20, 'provident', 'Molestiae exercitationem culpa quia qui. Reiciendis in deserunt velit voluptates. Ipsam qui est praesentium veniam alias ut neque.', 173056654, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (21, 'ratione', 'Dignissimos voluptatum quia ut. Illo illo id libero numquam pariatur sapiente quas. Doloribus possimus aliquid expedita consequatur quia. Et voluptas deleniti dolores sit qui dicta laudantium.', 1171429, 'est', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (22, 'veniam', 'Rerum autem unde doloremque est. Est et mollitia vitae repellendus qui enim. Eius maxime fugiat laudantium explicabo exercitationem. Expedita inventore dolorem tempore.', 1350784, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (23, 'delectus', 'Harum voluptas sed unde qui eos magni. Et officiis placeat quis itaque exercitationem minus quis. Quasi voluptatem fugiat consequatur natus aliquid id velit.', 6, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (24, 'non', 'Amet possimus quibusdam quis atque aut et. Et sunt fugiat totam nobis. Voluptate rem quod asperiores.', 364647, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (25, 'necessitatibus', 'Provident exercitationem quam minus. Laboriosam veritatis aut consequatur praesentium accusamus. Placeat ut explicabo esse.', 27, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (26, 'vitae', 'Id sunt debitis maiores voluptas vel aliquid. Aliquid sapiente quas quidem totam aut molestias quibusdam. Omnis et doloremque tempora sed harum sit. Est temporibus molestiae odit nisi voluptatem consequatur.', 0, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (27, 'dolores', 'Quisquam eum nisi odio recusandae inventore. Enim expedita dolor et maxime. Fugiat doloribus cum nisi iusto.', 75358, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (28, 'est', 'Nulla repudiandae quasi dolorem sequi eaque nihil. Et et officiis laborum. Et quo commodi non perspiciatis sit facere optio. Dignissimos est sit non aut. Saepe et rerum beatae ea quidem.', 1, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (29, 'rerum', 'Eveniet soluta odit sapiente necessitatibus. Facilis ab aliquam nisi expedita. Ab totam id corporis omnis.', 51, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (30, 'mollitia', 'Ipsa nobis voluptatem tenetur voluptatem et. Adipisci repellendus quod dolorum repudiandae eligendi debitis. Laborum in ut quos illo adipisci dolor. Accusantium id exercitationem quo molestiae velit.', 8203748, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (31, 'doloremque', 'Quidem error et culpa atque tempora dolores. Nam cupiditate vitae quisquam sed quidem et impedit. Cumque ut est aliquam nam soluta.', 44287, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (32, 'quam', 'Excepturi suscipit ad reiciendis accusamus et ut. Quam nihil sequi vel labore eum. Reiciendis sit aut eaque minima.', 0, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (33, 'at', 'Quos asperiores odit animi voluptas. Sed ipsam nobis vero aliquid. Ut similique in assumenda ad et assumenda nihil. Aspernatur eos vitae omnis. Sunt ab libero aliquam culpa aliquam.', 16, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (34, 'illum', 'Autem molestias consequatur sed natus qui. Voluptas adipisci ut temporibus libero autem consequatur in. Voluptates sed vitae ut earum. Fuga officiis ut velit quam unde atque qui aut.', 48, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (35, 'aliquam', 'Ea fugit rerum quia ut. Eligendi libero reprehenderit iste eum voluptas beatae sequi modi. Unde dolore sit labore cumque labore. Iste necessitatibus non maxime amet voluptatum harum.', 0, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (36, 'dolore', 'Mollitia ut deleniti vel odit. Adipisci quos doloribus ea et. Excepturi quas sed quidem quo veniam porro quas ducimus.', 0, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (37, 'illo', 'Iste quia totam aut labore magni ullam. Unde qui dolores totam in. Dolorem ratione optio aliquid eum aliquam.', 50, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (38, 'voluptatum', 'Quam ipsum non adipisci sint. Et et pariatur similique impedit ut. At iure pariatur perferendis facere earum eligendi.', 5, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (39, 'soluta', 'Esse praesentium animi ut ducimus voluptas soluta ipsa. Consequuntur voluptatibus quia dolor pariatur. Officiis quo quas dolorem cupiditate qui inventore debitis voluptates. Et animi eaque sunt tempora incidunt.', 0, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (40, 'adipisci', 'Eos et qui ut quis enim quo aut. Sunt consequuntur nam explicabo velit. Hic sint distinctio nihil illo odit facilis voluptatem.', 276739298, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (41, 'iusto', 'Culpa dignissimos consequuntur ducimus. Inventore repellat eum odit dolores perferendis. Est consequatur hic maiores.', 5, 'est', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (42, 'facilis', 'Quia et harum non et voluptatem. Occaecati sequi maiores voluptates est est quos accusantium. At nesciunt est cumque id natus cum incidunt.', 4, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (43, 'laudantium', 'Cupiditate vel dignissimos est ex eaque at. Asperiores quia molestiae nemo aperiam dolorem. Debitis eveniet delectus voluptatem ad.', 2, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (44, 'vel', 'Eaque autem qui in repudiandae impedit. Nihil vel voluptatum sit nam magnam et. Repellat consectetur est quae consectetur amet eos vitae. Et est aut impedit placeat sed odio.', 34307, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (45, 'sit', 'Officiis molestiae sapiente qui provident. Occaecati esse reiciendis sunt. Laborum nostrum ut et sapiente blanditiis explicabo.', 221951, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (46, 'eius', 'Ut cum nulla et quisquam expedita praesentium. Et quia et voluptatibus et dolor. Ullam molestias quisquam explicabo rem.', 358, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (47, 'iure', 'Ut molestiae rem est et quisquam exercitationem nisi. Deleniti maxime corrupti in sed modi quia atque sunt. Nemo tempore quam veniam repellat.', 890, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (48, 'saepe', 'Aspernatur quae minima ea aut voluptas velit exercitationem maxime. Nulla quam ut aut et velit in nemo.', 11832, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (49, 'explicabo', 'Ipsa quas et ratione odio qui accusamus. Ducimus dignissimos voluptates consequuntur tempore qui rerum est animi. Aspernatur nulla maxime nulla illum dolores nulla.', 8, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (50, 'repudiandae', 'Nihil ut pariatur magnam. Dolore sit quidem quia ipsam. Voluptates nobis beatae nam velit occaecati labore tempora. Odit et numquam laboriosam dolores.', 1, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (51, 'cupiditate', 'Libero officiis sed ipsa vitae dolorem vel magnam. Facere quis nam magnam ipsam tempora. Voluptas quisquam commodi quaerat.', 13342, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (52, 'quo', 'Fugit et sed aut. Exercitationem qui repellendus ut magni accusantium vitae velit error. Provident tenetur esse debitis non nulla blanditiis cupiditate enim. Aut delectus voluptatum in ut vel molestiae consequatur.', 10, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (53, 'omnis', 'Ea est voluptatum voluptas aut repellendus. Est in ut ea voluptatem aut aut modi qui. Impedit exercitationem nihil cum.', 8554921, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (54, 'magni', 'Quia neque et enim quam. In itaque consectetur sunt reprehenderit. Consequatur eveniet id aperiam pariatur. Doloribus esse minus quam sit dolor quasi a.', 2838795, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (55, 'libero', 'Omnis sit sit recusandae odit aut. Inventore dolore quis impedit dolorum rerum.', 4626710, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (56, 'commodi', 'Qui consequatur veniam non harum itaque quae ut. Et dolorem tenetur qui dolorem tempore maxime odio. Itaque nihil praesentium aut exercitationem recusandae.', 1265741, 'est', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (57, 'occaecati', 'Aliquid dignissimos illo qui cupiditate labore. Qui dolor doloribus assumenda. Ducimus quo quaerat alias aut dolorem maiores aut quos. Nostrum iure qui fugit animi cupiditate.', 5, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (58, 'id', 'Est qui fuga ut omnis id. Quia id repudiandae in et eaque in. Perferendis qui commodi molestiae veritatis quas. Aut ut quis expedita quasi esse.', 2, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (59, 'accusamus', 'Aut iure veritatis recusandae dolores. Dicta sed veniam recusandae eum repellendus aut commodi exercitationem. Neque commodi rerum incidunt. Veritatis cupiditate dolor beatae rem accusamus itaque.', 5, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (60, 'temporibus', 'Et neque iusto enim quidem sit quos id. Ipsum eius nemo ab et rerum. Autem dolorem dolorem voluptas aliquid a.', 98816, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (61, 'voluptates', 'Voluptas iste cum non enim ea. Officia excepturi ut officiis sint et. Minus dolores quam molestiae molestiae id.', 12, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (62, 'debitis', 'Est quo blanditiis ipsum esse qui debitis laborum veniam. Cupiditate praesentium aspernatur est nostrum perspiciatis enim omnis. Magnam sed aut veniam voluptatem sed.', 23, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (63, 'consectetur', 'Autem quam est dolorem voluptate nisi. Sequi veritatis dolorum ex ut a. Officiis eum necessitatibus quia modi quis velit quo. Architecto ducimus nemo illo autem earum explicabo aut. Possimus est asperiores ipsam quaerat minus nam ratione.', 15378764, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (64, 'ab', 'Consequatur vero distinctio quasi aut non nobis. Fuga neque aut repellendus tenetur. Ullam deserunt voluptatem culpa molestiae.', 5326365, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (65, 'neque', 'Sit non ea dolor sint debitis voluptatibus. Ut est facilis quidem consequatur. In inventore culpa hic.', 1, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (66, 'qui', 'Aut qui itaque sint non et et et. Magni libero itaque aut quia earum esse aut. Provident iste et maxime eos. Hic facere necessitatibus consequatur amet neque et quisquam. Porro ut praesentium libero.', 34616, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (67, 'cumque', 'Autem enim earum voluptatem dolore odio aut voluptatem tempore. Consequatur modi quis quia in fugiat id sint. Necessitatibus consequatur quia quos rem est a consequatur.', 4, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (68, 'incidunt', 'Ut officiis dolores cumque libero id eum. Libero rerum odio incidunt aperiam quia sed dolores. Doloribus qui occaecati est vel neque deserunt. Quia voluptatem deleniti amet.', 0, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (69, 'corporis', 'Enim aut illum vitae ullam quia qui. Quasi rem distinctio dolorem recusandae qui qui. Dolorum et vel voluptas eaque et modi dolor. Similique ipsam eligendi et quam architecto.', 342, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (70, 'animi', 'Dicta vero placeat magnam perspiciatis occaecati. Aut et repellat error ea consequuntur. Porro doloremque et est nam vitae facilis illo. Possimus a expedita non ut quae.', 182070058, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (71, 'minima', 'Est est sunt voluptatum quia id non harum nemo. Unde natus accusamus id architecto molestiae. Sint accusamus quis iusto aliquam.', 142441, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (72, 'nulla', 'Necessitatibus et et voluptatum architecto quidem et maxime. Omnis voluptate suscipit rerum reprehenderit blanditiis eum doloribus. Et tempore dolore voluptas aliquam id ratione fugit. Repudiandae voluptatum inventore quisquam officia officiis.', 99158050, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (73, 'voluptas', 'Ut libero et vero deleniti facilis non cum aut. Et ut praesentium debitis cupiditate cumque omnis qui. Cum possimus sed dolor praesentium delectus. Ex veniam ullam sint illum.', 0, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (74, 'nisi', 'Ut omnis et sequi amet illum id sed. Error molestiae eum voluptas sed sed et explicabo. Perspiciatis dolor qui iure dolores delectus.', 152211975, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (75, 'earum', 'Excepturi praesentium et vel tenetur nam voluptas. Ea minima rem eum odit. Enim repellat sed quas in ut. Omnis suscipit quia et aut vel asperiores exercitationem.', 0, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (76, 'modi', 'Et quis qui veniam eius at velit. Assumenda architecto nisi laudantium quis omnis. Et quo laborum aspernatur ut illum consectetur quos.', 236, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (77, 'excepturi', 'Facere minus ut quam. Omnis id recusandae quia vitae molestias et quis. Dolore ipsum inventore praesentium reprehenderit molestiae sed. Ut ut tenetur adipisci deleniti dolore aspernatur.', 45075405, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (78, 'repellat', 'Voluptatibus est ut natus magni facilis et commodi delectus. Voluptatem sed asperiores corporis quasi amet. Velit minima id eos sunt reprehenderit vel.', 651362, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (79, 'quod', 'Quia accusamus nemo quod. At aliquam at harum tempore neque aspernatur. Et itaque officiis perferendis veniam.', 9401058, 'unde', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (80, 'sed', 'Vero blanditiis at ipsam totam error aperiam aut in. Et incidunt amet consequuntur fugit. Enim provident enim corporis et dolores nisi. Iure suscipit reiciendis quibusdam ea nemo dolores. Molestias omnis eum ipsam expedita rem.', 2891, 'velit', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (81, 'ut', 'Tenetur enim rem temporibus nesciunt alias iusto. Ut id harum dolor distinctio inventore architecto. Dolore excepturi distinctio harum nam aut velit. Animi temporibus quia reiciendis dicta cum voluptas.', 18, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (82, 'ad', 'Quis provident et magnam consequatur dolorum adipisci. Eum mollitia beatae pariatur blanditiis. Dicta enim ipsa excepturi mollitia. Nobis aut cupiditate vel quo fuga qui provident.', 1661, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (83, 'laboriosam', 'Tempore suscipit commodi magni ut voluptas omnis. Optio ullam in labore eius quisquam. Soluta non ratione exercitationem. Accusamus quasi sit odio facere.', 34, 'molestias', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (84, 'accusantium', 'Asperiores qui molestiae voluptatibus. Id dolorem id sunt tenetur quasi. Labore asperiores itaque repellendus. Et similique voluptas ut necessitatibus nisi.', 1, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (85, 'sequi', 'Architecto explicabo repudiandae atque consequatur voluptatem esse atque. Libero laborum totam doloremque corrupti. Tempora aut cum voluptatem. Debitis aut blanditiis qui rerum quae sint consequatur.', 3152622, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (86, 'itaque', 'Nulla enim aut eaque consequatur accusantium. Enim ipsum laudantium necessitatibus aperiam id delectus. Error quae inventore et id quia. Beatae maxime ea quo dignissimos commodi. Alias ex velit id veritatis.', 20274, 'est', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (87, 'quis', 'Aliquid nihil in ad deleniti corporis. Quos dolor asperiores adipisci et ut excepturi. Architecto labore earum vero commodi minima laudantium in ducimus.', 6334549, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (88, 'fugiat', 'Earum dolores ipsa sed aperiam et. Et est modi et quia enim. Dolorem officia sit et reprehenderit.', 0, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (89, 'optio', 'Atque debitis iusto vel. Dignissimos sapiente hic vel ullam perspiciatis animi corporis atque. Facere est ratione molestiae quisquam aliquid veritatis quia. Consequatur iure et vel eius voluptates perspiciatis temporibus nemo.', 9819220, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (90, 'possimus', 'Facere sunt dolorem nam iure velit adipisci et. Ea ut reiciendis blanditiis et. Dolores eum consequatur aut odio eum.', 0, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (91, 'deleniti', 'Nostrum eligendi magnam vero eligendi velit. Impedit voluptas quo est.', 22582, 'est', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (92, 'alias', 'Dolores aliquam error voluptas et explicabo. Perspiciatis quia qui aut exercitationem ut. Ut cum unde repellat consequatur harum magni sed deleniti. Tenetur sequi odit et.', 174812838, 'hic', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (93, 'nobis', 'Aspernatur dolor in sint. Nam voluptatem iure commodi. Perferendis eos officiis cupiditate totam id.', 54912, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (94, 'molestias', 'Voluptatibus quisquam autem qui non dolorem. Autem rerum deserunt est commodi nihil id. Aut provident atque consequatur enim omnis dolorem consequuntur. Et dicta in adipisci.', 58, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (95, 'in', 'Perferendis et repudiandae natus repudiandae suscipit. Dolores repudiandae et dolores fugiat sint. Sit mollitia qui assumenda voluptatum provident molestiae numquam. Iste in eveniet facilis corrupti nulla et perspiciatis.', 52119020, 'velit', 1);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (96, 'nam', 'Et ut itaque repudiandae totam quam sed. Et laudantium aut a sit ut voluptatibus. Molestiae nisi ut iusto commodi voluptates. Quisquam ut ipsa cupiditate.', 1, 'est', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (97, 'tempore', 'Quod et recusandae eos beatae exercitationem. Placeat suscipit est provident dolorum est sapiente itaque aperiam.', 6, 'hic', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (98, 'porro', 'Sunt soluta enim animi. In est voluptatem eos in rem voluptas.', 397682789, 'molestias', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (99, 'labore', 'Nemo et ducimus sed id placeat. Odio consequatur aut nesciunt ut facilis enim ducimus. Fuga corporis qui pariatur.', 91726752, 'unde', 0);
INSERT INTO `meals` (`id`, `name`, `description`, `price`, `type`, `is_meal_of_the_day`) VALUES (100, 'ex', 'Corrupti atque ullam iste ducimus sed. Et ad repudiandae voluptas molestiae velit sequi commodi. Voluptates quos ut sit ad.', 36085, 'velit', 0);


#
# TABLE STRUCTURE FOR: users
#

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `password` int(11) NOT NULL,
  `role` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

